implement output format html for cocoa widgetset
EpiData-dk/analysis pull request #4
Opened 2021-12-30 14:32 UTC by charlesknightsbridge

Requires components from LCLWebBrowser which implement direct calls to MacOS api for HTML display; uses native handlers for copying html on screen

2021-12-30 15:48 UTC, torstenchr commented
All files/folders name .DS_Store are mac specific and should not be part of the commit.

2021-12-30 16:03 UTC, charlesknightsbridge commented
I’ll try to skip them next time. I’ll see if there is a setting in GitHub Desktop to skip hidden files.

Jamie

> On Dec 30, 2021, at 10:48 AM, Torsten Bonde Christiansen ***@***.***> wrote:
> 
> ﻿
> All files/folders name .DS_Store are mac specific and should not be part of the commit.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.

2021-12-30 17:28 UTC, torstenchr commented
I have removed the folders in question such that they will not be part of the final merge. Please make sure to do a "git pull" before any further work on the branch.

2022-07-06 19:06 UTC, charlesknightsbridge commented
Would not merge because of differences in .gitignore! That's been resolved, so over to you.

2022-07-13 15:58 UTC, torstenchr requested changes
Once the .gitignore file has been reverted back to before the PR is ready for approval.

2022-07-13 18:16 UTC, charlesknightsbridge commented on .gitignore
> -src/grammar/*.cgt
It's mystery to me...no doubt my fault, but done by the github app. I forget that .gitignore is in the repository.

2022-07-13 18:26 UTC, charlesknightsbridge commented
Change committed; back to you, Torsten. I can't approve and it won't go automatically.

2022-07-13 18:29 UTC, torstenchr approved these changes
Perfect!

2022-07-22 02:41 UTC, merged