Fix set output font not applied to html output
EpiData-dk/analysis pull request #70
Opened 2024-04-27 18:44 UTC by charlesknightsbridge

On the Mac, set "output font name" has never changed the font on screen or in a saved file. Now, the standard embedded CSS has been changed from a constant to a constant string, so that it can be modified. Changes work for Darwin build; I assume they will for Windows and Linux, but not verified.

lpi and lpr files not include Hi DPI awareness

2024-04-29 17:59 UTC, torstenchr requested changes
This pull request is close to doing two things at once. 
1) Updating the UI with setting the DPI aware options and enabling scaling.
2) Adding handling of SET FONT SIZE/NAME

Preferably this should have been split into two seperate pull requests. If either of the changes end up causing unforeseen problems we would have to revert both fixes instead of one.

2024-04-29 18:27 UTC, charlesknightsbridge commented on src/main.lfm
> +      OnClick = Button2Click
See below

2024-04-29 18:27 UTC, charlesknightsbridge commented on src/main.lfm
> +      OnClick = Button3Click
See below

2024-04-29 18:29 UTC, charlesknightsbridge commented on src/main.pas
> +//    EnableAutoSizing;
I was trying to get the cursor back into the command line (here and in another procedure). It doesn't seem to be working for me. I suspected something with AutoSizing.
But this is still unsolved...

2024-04-29 18:41 UTC, charlesknightsbridge commented on src/main.lfm
> +      OnDblClick = HistoryListBoxDblClick
Lazarus seems to have done all of this on its own. It looks like it reordered some of those commands.

2024-05-06 17:36 UTC, torstenchr requested changes

2024-05-06 17:36 UTC, torstenchr commented on src/main.lfm
> +      OnDblClick = HistoryListBoxDblClick
Can you remove the unused method?

2024-05-06 17:36 UTC, torstenchr commented on src/main.pas
> +//    EnableAutoSizing;
Are you actively looking into getting the cursor back or should this code be reverted back?

2024-05-06 18:32 UTC, charlesknightsbridge commented
I'm going to redo this. I don't know how the extra buttons, etc. came into it.

2024-05-06 18:32 UTC, closed without merging